# Generated by Django 4.2.5 on 2023-12-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='flat',
            field=models.PositiveIntegerField(null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='place',
            name='house',
            field=models.PositiveIntegerField(null=True, verbose_name='Дом'),
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
