# Generated by Django 4.2.5 on 2023-11-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_mediamodel_type'),
        ('re_objects', '0002_engineeringservices_fencing_foundation_landcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reobject',
            name='engineering_services',
        ),
        migrations.AlterField(
            model_name='reobject',
            name='category',
            field=models.ForeignKey(help_text='Дом, Квартира, Участок', null=True, on_delete=django.db.models.deletion.CASCADE, to='re_objects.category', verbose_name='Категория объекта'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='fencing',
            field=models.ForeignKey(help_text='Горы, Шморы', null=True, on_delete=django.db.models.deletion.CASCADE, to='re_objects.fencing', verbose_name='Ограждение'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='foundation',
            field=models.ForeignKey(help_text='Блоки, Лента, Плита', null=True, on_delete=django.db.models.deletion.CASCADE, to='re_objects.foundation', verbose_name='Фундамент'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='land_category',
            field=models.ForeignKey(help_text='Комерческая', null=True, on_delete=django.db.models.deletion.CASCADE, to='re_objects.landcategory', verbose_name='Категория земель'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='ownership',
            field=models.ForeignKey(help_text='От собственника, Ипотека, и.т.д', null=True, on_delete=django.db.models.deletion.CASCADE, to='re_objects.ownership', verbose_name='Собственность'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='relief_area',
            field=models.ForeignKey(help_text='Горы, Шморы', null=True, on_delete=django.db.models.deletion.CASCADE, to='re_objects.reliefarea', verbose_name='Рельеф участка'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='type_house',
            field=models.ForeignKey(help_text='Комерческая, ИЖС, Жилая', null=True, on_delete=django.db.models.deletion.CASCADE, to='re_objects.typehouse', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='village_fences',
            field=models.ForeignKey(help_text='Да, нет', null=True, on_delete=django.db.models.deletion.CASCADE, to='re_objects.villagefences', verbose_name='Ограждение поселка'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='wall_material',
            field=models.ForeignKey(help_text='Кирпич, Панель, Пеноблок', null=True, on_delete=django.db.models.deletion.CASCADE, to='re_objects.wallmaterial', verbose_name='Материал стен'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='windows_orientation',
            field=models.ForeignKey(help_text='Запад, Север, Восток, и.т.д', null=True, on_delete=django.db.models.deletion.CASCADE, to='re_objects.windowsorientation', verbose_name='Ориентация окон'),
        ),
        migrations.CreateModel(
            name='ReObjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.mediamodel')),
                ('re_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_objects.reobject')),
            ],
        ),
        migrations.CreateModel(
            name='ReObjectEngineeringServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineering_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_objects.engineeringservices')),
                ('re_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_objects.reobject')),
            ],
        ),
    ]
