# Generated by Django 4.2.5 on 2023-11-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0003_remove_reobject_engineering_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefarea',
            name='value',
            field=models.CharField(help_text='Рельеф участка', verbose_name='Рельеф участка'),
        ),
    ]
