# Generated by Django 4.2.5 on 2023-11-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
        ('re_objects', '0004_alter_reliefarea_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reobject',
            name='category',
            field=models.ForeignKey(help_text='Дом, Квартира, Участок', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.category', verbose_name='Категория объекта'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='fencing',
            field=models.ForeignKey(help_text='Горы, Шморы', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.fencing', verbose_name='Ограждение'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='foundation',
            field=models.ForeignKey(help_text='Блоки, Лента, Плита', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.foundation', verbose_name='Фундамент'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='land_category',
            field=models.ForeignKey(help_text='Комерческая', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.landcategory', verbose_name='Категория земель'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='ownership',
            field=models.ForeignKey(help_text='От собственника, Ипотека, и.т.д', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.ownership', verbose_name='Собственность'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='relief_area',
            field=models.ForeignKey(help_text='Горы, Шморы', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.reliefarea', verbose_name='Рельеф участка'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='type_house',
            field=models.ForeignKey(help_text='Комерческая, ИЖС, Жилая', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.typehouse', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='village_fences',
            field=models.ForeignKey(help_text='Да, нет', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.villagefences', verbose_name='Ограждение поселка'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='wall_material',
            field=models.ForeignKey(help_text='Кирпич, Панель, Пеноблок', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.wallmaterial', verbose_name='Материал стен'),
        ),
        migrations.AlterField(
            model_name='reobject',
            name='windows_orientation',
            field=models.ForeignKey(help_text='Запад, Север, Восток, и.т.д', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.windowsorientation', verbose_name='Ориентация окон'),
        ),
        migrations.AlterField(
            model_name='reobjectengineeringservices',
            name='engineering_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.engineeringservices'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='EngineeringServices',
        ),
        migrations.DeleteModel(
            name='Fencing',
        ),
        migrations.DeleteModel(
            name='Foundation',
        ),
        migrations.DeleteModel(
            name='LandCategory',
        ),
        migrations.DeleteModel(
            name='Ownership',
        ),
        migrations.DeleteModel(
            name='ReliefArea',
        ),
        migrations.DeleteModel(
            name='TypeHouse',
        ),
        migrations.DeleteModel(
            name='VillageFences',
        ),
        migrations.DeleteModel(
            name='WallMaterial',
        ),
        migrations.DeleteModel(
            name='WindowsOrientation',
        ),
    ]
