# Generated by Django 4.2.5 on 2023-12-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re_objects', '0005_alter_reobject_category_alter_reobject_fencing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reobject',
            options={'verbose_name': 'Объекты недвижимости', 'verbose_name_plural': 'Объекты недвижимости'},
        ),
    ]
