# Generated by Django 4.2.5 on 2023-12-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_objectdescription'),
        ('re_objects', '0006_alter_reobject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reobject',
            name='object_description',
            field=models.ForeignKey(help_text='Текст в markdown', null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.objectdescription', verbose_name='Описание объекта'),
        ),
    ]
