# Generated by Django 4.2.5 on 2023-11-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EngineeringServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Наличие инженерных услуг', max_length=50, verbose_name='Инженерные услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Fencing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Ограждение участка', max_length=50, verbose_name='Ограждение участка')),
            ],
        ),
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Тип фундамента', max_length=50, verbose_name='Тип фундамента')),
            ],
        ),
        migrations.CreateModel(
            name='LandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Категория земли', max_length=50, verbose_name='Категория земли')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Форма собственности объекта', max_length=50, verbose_name='Форма собственности')),
            ],
        ),
        migrations.CreateModel(
            name='ReliefArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Рельеф участка', verbose_name='Рельеф участка')),
            ],
        ),
        migrations.CreateModel(
            name='TypeHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VillageFences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Заборы в деревне', max_length=50, verbose_name='Заборы в деревне')),
            ],
        ),
        migrations.CreateModel(
            name='WallMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Материал стен', max_length=50, verbose_name='Материал стен')),
            ],
        ),
        migrations.CreateModel(
            name='WindowsOrientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Ориентация окон', max_length=50, verbose_name='Ориентация окон')),
            ],
        ),
    ]
