# Generated by Django 4.2.5 on 2023-12-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория объекта', 'verbose_name_plural': 'Категория объекта'},
        ),
        migrations.AlterModelOptions(
            name='engineeringservices',
            options={'verbose_name': 'Инженерные сети', 'verbose_name_plural': 'Инженерные сети'},
        ),
        migrations.AlterModelOptions(
            name='fencing',
            options={'verbose_name': 'Ограждение участка', 'verbose_name_plural': 'Ограждение участка'},
        ),
        migrations.AlterModelOptions(
            name='foundation',
            options={'verbose_name': 'Тип фундамента', 'verbose_name_plural': 'Тип фундамента'},
        ),
        migrations.AlterModelOptions(
            name='landcategory',
            options={'verbose_name': 'Категория земель', 'verbose_name_plural': 'Категория земель'},
        ),
        migrations.AlterModelOptions(
            name='ownership',
            options={'verbose_name': 'Тип собственности', 'verbose_name_plural': 'Тип собственности'},
        ),
        migrations.AlterModelOptions(
            name='reliefarea',
            options={'verbose_name': 'Рельеф участка', 'verbose_name_plural': 'Рельеф участка'},
        ),
        migrations.AlterModelOptions(
            name='typehouse',
            options={'verbose_name': 'Тип объекта', 'verbose_name_plural': 'Тип объекта'},
        ),
        migrations.AlterModelOptions(
            name='villagefences',
            options={'verbose_name': 'Ограждения в поселке', 'verbose_name_plural': 'Ограждения в поселке'},
        ),
        migrations.AlterModelOptions(
            name='wallmaterial',
            options={'verbose_name': 'Материал стен', 'verbose_name_plural': 'Материал стен'},
        ),
        migrations.AlterModelOptions(
            name='windowsorientation',
            options={'verbose_name': 'Ориентация окон', 'verbose_name_plural': 'Ориентация окон'},
        ),
        migrations.AlterField(
            model_name='engineeringservices',
            name='value',
            field=models.CharField(help_text='Наличие инженерных сетей', max_length=50, verbose_name='Инженерные сети'),
        ),
        migrations.AlterField(
            model_name='villagefences',
            name='value',
            field=models.CharField(help_text='Ограждения в поселке', max_length=50, verbose_name='Ограждения в поселке'),
        ),
    ]
