# Generated by Django 4.2.5 on 2023-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Используйте маркдаун', max_length=2500, verbose_name='Описание объекта')),
            ],
            options={
                'verbose_name': 'Описание объекта',
                'verbose_name_plural': 'Описание объекта',
            },
        ),
    ]
