version: "3.9"
services:
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: ./docker/backend/dockerfile/Dockerfile.dev
        entrypoint: /usr/local/bin/entrypoint.sh
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        # ports:
        #     - "8000:8000"
        volumes:
            - ./backend:/usr/src/backend
            - ./docker/backend/fixtures/:/usr/src/fixtures
        depends_on:
            postgresql:
                condition: service_healthy
        restart: on-failure
        networks:
            - re_network

networks:
    re_network:
        driver: bridge
