version: "3.9"
services:
    postgresql:
        container_name: postgresql
        image: postgres:15-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=re
            - POSTGRES_DB=re
            - POSTGRES_PASSWORD=323232
        ports:
            - 5432:5432
        expose:
            - 5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U re"]
            interval: 5s
            timeout: 5s
            retries: 10
        networks:
            - re_network

volumes:
    postgres_data:
        driver: local
networks:
    re_network:
        driver: bridge
